# File: docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      # THAY ĐỔI QUAN TRỌNG: context bây giờ là '.' (thư mục hiện tại)
      # thay vì '../famrex-fe' như trước
      context: .
      dockerfile: Dockerfile
    restart: always

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Đường dẫn này bây giờ là tương đối từ thư mục gốc của project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend